config/routes.rb
Rails.application.routes.draw do

  resources :motivations
	resources :assessments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show]
  get '/reminders', to: 'users#reminder_settings' 

  root 'home#index'
end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
	belongs_to :user
end

app/models/motivation.rb
class Motivation < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	devise :omniauthable, :omniauth_providers => [:google_oauth2]
  has_one :assessment
  has_many :motivations 
  
  def email_is_daily?
    email_frequency == 0
  end
  
  def email_is_weekly?
    email_frequency == 1    
  end

  def needs_email?
    (email_is_daily? and (Time.now - 1.day) > last_email) ||
    (email_is_weekly? and (Time.now - 7.day) > last_email)
  end  

  def sms_is_daily?
    sms_frequency == 0
  end
  
  def sms_is_weekly?
    sms_frequency == 1    
  end

  def needs_sms?
    (sms_is_daily? and (Time.now - 1.day) > last_email) ||
    (sms_is_weekly? and (Time.now - 7.day) > last_email)
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, 
                                                            :last_name, 
                                                            :phone, 
                                                            :email, 
                                                            :email_frequency,
                                                            :sms_frequency,
                                                            :last_email,
                                                            :last_sms,
                                                            :password,
                                                            :password_confirmation
                                                            ) 
                                              }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, 
                                                                   :last_name, 
                                                                   :phone, 
                                                                   :email, 
                                                                   :email_frequency,
                                                                   :sms_frequency,
                                                                   :last_email,
                                                                   :last_sms,
                                                                   :password,
                                                                   :current_password,
                                                                   :password_confirmation
                                                                  ) 
                                                    }                                              
	end

  def after_sign_in_path_for(resource)
    @user
  end
  
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only:[ :show, :edit, :update, :destroy]

  def index
    @assessments = Assessment.all
  end

  def new
    @assessment = Assessment.new
  end

  def edit
  end

  def show
  end

  def create
    @user = current_user
    @assessment = Assessment.new(assessment_params)
    if @assessment.save
      redirect_to new_motivation_path, notice: "Saved succcessfully."
      UserMailer.explore_assessment_email(@user).deliver_now
    else
      render :new
    end
  end

  def update
    @user = current_user
    if @assessment.update
      redirect_to @assessment, notice: "Changes succcessfully saved."
      UserMailer.explore_assessment_email(@user).deliver_now
    else
      render :edit
    end
  end

  def destroy
    @assessment.destroy
    redirect_to current_user, notice: "Assessment was deleted."
  end

  private

  def set_assessment
    @assessment = Assessment.find(params[:id])
  end

  def assessment_params
    params.require(:assessment).permit(:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, 
                                       :passion_one, :passion_two, :passion_three, :passion_four, 
                                       :passion_five, :user_id).merge(user: current_user)
  end
end
  

app/controllers/callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
           email: data["email"],
           password: Devise.friendly_token[0,20]
        )
     end
    user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController
	before_action :set_motivation, only: [:show, :edit, :update, :destroy]
  def index
  	@motivations = Motivation.all
    @user = current_user
  end

  def new
  	@motivation = Motivation.new
  end

  def create
  	@motivation = Motivation.new(motivation_params)
  	if @motivation.save
  		redirect_to motivations_path, notice: "Submitted successfully"
  	else
  		render :new, notice: "There was a problem"
  	end
  end

  def show
  end

  def edit
  end

  def update
  	@motivation.update(motivation_params)
  	if @motivation.save
  		redirect_to motivations_path, notice: "Your changes were submitted successfully"
  	else
  		render :edit, notice: "There was a problem"
  	end
  end

  def destroy
  	@motivation.destroy
  	redirect_to motivations_path, notice: "Deleted successfully"
  end

  private

  def set_motivation
  	@motivation = Motivation.find(params[:id])
  end

  def motivation_params
  	params.require(:motivation).permit(:title, :body, :image).merge(user: current_user)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = current_user
  end

  def reminder_settings
  	@user = current_user
  end

end

app/helpers/add_last_remindedto_users_table_helper.rb
module AddLastRemindedtoUsersTableHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inspirations_helper.rb
module InspirationsHelper
end

app/helpers/passion_quizes_helper.rb
module PassionQuizesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assessments/_form.html.erb
<%= form_for @assessment do |f| %>
	<% if @assessment.errors.any? %>
		<div class="notice">
		<p>There was a problem:</p>
		<% @assessment.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	<% end %>	

	<p class="form-group">
		<%= f.text_area :q1, size: "20x20", placeholder: "Where are you? What are you doing? Who is around you?", required: true, class: "form-control" %>
	</p>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Assessments#edit</h1>
<p>Find me in app/views/assessments/edit.html.erb</p>

app/views/assessments/index.html.erb
<div class="assessment">
	<h1>Vision</h1>
		<p><%= @assessments.last.q1 %></p>
</div>

<%= link_to "Back", user_path(current_user) %>

app/views/assessments/new.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-8 col-md-offset-2">
			<h1 class="text-center">Explore</h1>
				<div class="questions">
					<div class="q1">
						<h3>Imagine that you have achieved your goal and are that successful version of yourself now. What can you see, hear and feel? – really associate yourself.</h3>

						<p>Describe, in as much detail as possible what you are seeing.</p>
						
						<%= form_for @assessment do |f| %>
							<% if @assessment.errors.any? %>
								<div class="notice">
								<p>There was a problem:</p>
								<% @assessment.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							<% end %>	

							<p class="form-group">
								<%= f.text_area :q1, size: "20x7", placeholder: "Where are you? What are you doing? Who is around you? Etc.", required: true, class: "form-control" %>
							</p>

					</div><!--/q1 -->					

					<h3>Now visualize the steps you took to get there, including the point where you are now, making that initial decision.</h3> 

					<p>Write down the steps you took</p>

					<p class="form-group">
						<%= f.text_area :q2, size: "20x7", required: true, class: "form-control" %>
					</p>					

					  <div class="form-group text-right">
					    <%= f.submit "Save", class: "btn btn-success btn-lg" %>
					  </div>
					<% end %>
				</div><!-- /questions -->
			</div><!-- /col-sm-6 -->
		</div><!-- /col-sm-8 -->	

	</div><!-- /row -->	
	<%= link_to "Back", user_path(current_user) %>		
</div><!-- /container -->

app/views/assessments/show.html.erb
<h1>assessments#show</h1>

app/views/home/index.html.erb
<div class="container">
  
<!-- START THE CAROUSEL -->
  <div class="row">
    <div class="col-sm-12">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>      
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img class="first-slide" src="http://brainsoftgroup.com/images/vision.png" alt="First slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Sprout</h1>
                <h2>Let your dreams take root</h2>
                <% if !current_user %>
                <p><%= link_to "Sign Up today", new_user_registration_path, class: "btn btn-lg btn-primary" %></p>
                <% end %>
              </div>
            </div>
          </div>
          <div class="item">
            <img class="second-slide" src="http://brainsoftgroup.com/images/vision.png" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Create A Clear Vision of Your Ideal Destination</h1>
                <p><a class="btn btn-lg btn-primary" href="#learnmore" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <img class="third-slide" src="http://brainsoftgroup.com/images/vision.png" alt="Third slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Conquer The Challenges In Your Life</h3>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div><!-- /.carousel -->
    </div><!-- /.col-md-12 -->
  </div><!-- /.row -->
<!-- /END THE CAROUSEL -->  


<!-- START THE FEATURETTES -->
  <div class="row featurette">
    <hr class="featurette-divider">
    <div class="col-md-7 success-story-1">
      <h2 class="featurette-heading">Lisa Smith<span class="text-muted">, Graduate Student</span></h2>
      <p class="lead">"Sprout has not only helped me to achieve goals, but more importantly, it has enabled me to discover who I am, what makes me tick, and what those goals really are. Sprout was able to find the hidden treasures that allow me to achieve those goals."</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" src="http://cdn1.theodysseyonline.com/files/2015/06/04/635690584083999001-1832628294_635683512724816093-1684666009_IMG_6834.imgopt500x65.JPG">
    </div>
  </div>

  <div class="row featurette">
    <hr class="featurette-divider">
    <div class="col-md-7 col-md-push-5 success-story-2">
      <h2 class="featurette-heading">Jane Doe<span class="text-muted">, Administrator</span></h2>
      <p class="lead">"I'm so glad that I started this journey. In so many areas of my life I have been able to make huge strides. I have lost 30 pounds with the help of Sprout. Sprout reminded me of my values and coached me in a gentle but firm way. I am so grateful for all Sprout has done for me and I will be telling everyone who wants to achieve more (and even those who don't know they want to) about the difference using Sprout has made. My business has increased and is ever increasing. I am more confident than I have ever been. I feel I have moved mountains."</p>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <img class="featurette-image img-responsive center-block" src="https://tttphotos.s3.amazonaws.com/production/uploads/user/profileimage/50815/largesquare_Headshot_in_Purple_flipped_face0.jpg">
    </div>
  </div>

  <div class="row featurette">
    <hr class="featurette-divider">
    <div class="col-md-7 success-story-3">
      <h2 class="featurette-heading">John Doe<span class="text-muted">, Physician</span></h2>
      <p class="lead">"Sprout has helped me to identify issues that have stood in the way of business success and assisted me in developing techniques for working around or through these issues. As someone who has gone through substantial change in my professional career over the past couple of years, I count on sprout to ensure that this transition continues to go smoothly."</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" src="http://cms.ipressroom.com.s3.amazonaws.com/214/files/20150/55414b67f6091d5fbf000002_Paliwal_Headshot_500px/Paliwal_Headshot_500px_mid.jpg" alt="Generic placeholder image">
    </div>
    <hr class="featurette-divider">
  </div>
<!-- /END THE FEATURETTES -->
<hr>
<!-- START COMPONENT SECTION -->
    <div class="row component-section" id="learnmore">
    <!-- Three columns of text below the carousel -->
          <div class="col-md-6">
            <div class="component">
              <img class="img-circle" src="http://indogermancropscience.com/images/vision.jpg" width="175" height="175">
              <div>
                <h3>Create Your Vision</h3>
                <p class="lead">A vision that not only inspires you, makes you feel hopeful, and optimistic, but is also specific, clear, and enourmously effective.</p>
              </div>
            </div><!-- /.component -->  

          </div><!-- /.col-lg-6 -->
            <div class="col-md-6">
              <div class="component">
              <img class="img-circle" src="http://www.kreativemines.com/uploads/PPC-Management-Services.png" width="175" height="175">
              <div>
                <h3>Conquer the Challenges In Your Life</h3>
                <p class="lead">Gain a better sense of where you are and how to get there</p>
              </div>
            </div><!-- /.component -->              
          </div><!-- /.col-lg-6 -->
        </div>
        <div class="row component-section">
          <div class="col-md-6">
            <div class="component">
              <img class="img-circle" src="https://www.anitian.com/wp-content/uploads/2015/05/chain.png" alt="Generic placeholder image" width="175" height="175">
              <div>
                <h3>Call In Your Strengths</h3>
                <p class="lead">Cultivate confidence by finding your strengths, talents, and abilities.</p>
              </div>
            </div><!-- /.component --> 
          </div><!-- /.col-lg-6 -->

          <div class="col-md-6">
            <div class="component">
              <img class="img-circle" src="http://www.horizonbaptist.com/hp_wordpress/wp-content/uploads/2014/08/grow.png" width="175" height="175">
              <div>
                <h3>Foster Positivity</h3>
                <p class="lead">Positive emotions are the active ingredient in responding to adversity. </p>
              </div>
            </div><!-- /.component --> 
          </div><!-- /.col-lg-6 -->     
        </div><!--/.row component-description -->
      </div><!--/.col-md-12 -->
    </div><!--/.row component-section -->    
  </div><!--/.container -->

app/views/inspirations/_form.html.erb
<div class="form-style-6"> 

<%= form_for @inspiration, html: { multipart: true } do |f| %>
	<p><%= f.label :title, "Upload an Image" %>
		<%= f.file_field :image, required: true %>
	</p>
  <p><%= f.label :title %><br>
      <%= f.text_field :title %>
  </p>

  <p><%= f.label :body %><br>
      <%= f.text_area :body, rows: 10, col: 50 %>
  </p>

  <p><%= f.submit %></p>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<%= favicon_link_tag 'favicon.ico' %>	
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sprout</title>	
	<%= csrf_meta_tags %>	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
	<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

	<!-- Latest compiled and minified JavaScript -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>	
  
</head>
<body>

<div class="container">
	<div class="navbar-wrapper">
	  <div class="container">

	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <div class="navbar-brand">
	    	      	<%= link_to image_tag("sproutlogo2.png"), root_path  %>
    	      		<% if current_user %>
									<span>Hello <%= current_user.first_name %></span>
								<% end %>
				    </div>  
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
	          <div class="nav navbar-nav navbar-right">
	            <% if !current_user %>            
		            <li><%= link_to "Log In", user_session_path%></li>
    				    <li><%= link_to "Sign Up", new_user_registration_path %>
			          <li>
	            <% else %>
	            	<li><%= link_to "My Profile", user_path(current_user) %></li>
		            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
						</div>
		          <% end %>
	        </div>
	      </div>
	    </nav>

	  </div>
	</div>	

	<% if flash[:notice] %>
		<div class="notice fade in">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		    <span class="sr-only">Close</span>
		  </button>
			<%= flash[:notice] %>
		</div>
	<% end %>
	<% if flash[:alert] %>
		<div class="notice fade in">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		    <span class="sr-only">Close</span>
		  </button>		
			<%= flash[:alert] %>
		</div>
	<% end %>

<%= yield %>

</div>
</div> <!-- container -->
</body>
</html>

app/views/motivations/edit.html.erb
<div class="container">

  <div class="col-sm-2">
    <ul class="nav nav-sidebar nav-stacked">
      <li><%= link_to "Vision", assessments_path %></li>
      <li><%= link_to "Motivation", motivations_path %></li>
      <li><%= link_to "Action Plan", user_path %></li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <li><%= link_to "Reminder Settings", reminders_path %></li>        
    </ul>
  </div>

	<div class="col-md-6 col-md-offset-2">
		<h1 class="text-center">Edit</h1>
			<p class="text-center"><%= image_tag @motivation.image.url(:medium) %></p>
			<%= render 'form' %>
	</div>	
</div>	

app/views/motivations/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2">
		  <ul class="nav nav-sidebar nav-stacked">
		    <li><%= link_to "Vision", assessments_path %></li>
		    <li><%= link_to "Motivation", motivations_path %></li>
		    <li><%= link_to "Action Plan", @user %></li>
		    <li><%= link_to "Account Settings", edit_user_registration_path %></li>
		    <li><%= link_to "Reminder Settings", reminders_path %></li>        
		  </ul>
		</div>


		<div class="col-md-6">
			<%= render @user.motivations.reverse %>
		</div>
	</div>
</div>

app/views/motivations/new.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="text-center">Motivational Board</h1>
		<%= render 'form' %>
	</div>	
</div>	
<div class="container">
	<%= link_to "Cancel", user_path(current_user) %>
</div>	

app/views/motivations/show.html.erb
<div class="container">

  <div class="col-md-2">
    <ul class="nav nav-sidebar nav-stacked">
      <li><%= link_to "Vision", assessments_path %></li>
      <li><%= link_to "Motivation", motivations_path %></li>
      <li><%= link_to "Action Plan", user_path %></li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <li><%= link_to "Reminder Settings", reminders_path %></li>        
    </ul>
  </div>

	<div class="col-md-6">
		<%= render @motivation %> 
	</div>
</div>
<div class="container text-right">	
	<%= link_to 'Edit', edit_motivation_path(@motivation), class: "btn btn-success btn-lg" %>
	<%= link_to "Delete", motivation_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg"  %>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-3">
      <ul class="nav nav-sidebar nav-stacked">
        <li><%= link_to "Vision", assessments_path %></li>
        <li><%= link_to "Motivation", motivations_path %></li>
        <li><%= link_to "Action Plan", user_path %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Reminder Settings", reminders_path %></li>        
      </ul>
    </div><!-- col-sm-3 sidebar -->

    <div class="col-sm-9">
      <h1 class="page-header">Dashboard</h1>

          <div class="row component-section">
          <div class="col-md-4">
            <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>Explore</h3>
              <p>First, you need to agree a Goal and Outcome. What is your goal? Make the goal specific, measurable and realistic. You have to believe in your goal, also be consistent don’t have a goal that conflicts with another goal or you will lose motivation in an instant.</p>
              <%= link_to 'My Goal', new_assessment_path, class: "btn btn-success" %>
            </div><!-- /.component -->  

          </div><!-- /.col-lg-6 -->
            <div class="col-md-4">
              <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>Motivators</h3>
              <p>Making changes is a natural life progression, helping you stay fresh and motivated, when you want to make a change you first need to ask yourself “why do you want to make a change?”</p>
              <%= link_to 'Motivators', new_motivation_path, class: "btn btn-success" %>
            </div><!-- /.component -->              
          </div><!-- /.col-lg-6 -->
            <div class="col-md-4">
              <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>Challenges</h3>
              <p>To achieve your goal you need to understand the Reality of your current situation, skills, time constraints, attitudes, process and how far or near you are to achieving your goal.</p>
              <%= link_to 'Challenges', root_path, class: "btn btn-success" %>
            </div><!-- /.component -->              
          </div><!-- /.col-lg-6 -->          
        </div>
        <div class="row component-section">
          <div class="col-md-4">
            <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>My Values</h3>
              <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
              <%= link_to 'My Values', root_path, class: "btn btn-success" %>
            </div><!-- /.component --> 
          </div><!-- /.col-lg-6 -->

          <div class="col-md-4">
            <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>Support</h3>
              <p>You need a team to make it happen. Your team can be from your customers, employees, advocates, partners, colleagues, community, friends and family.</p>
              <%= link_to 'Support', root_path, class: "btn btn-success" %>
            </div><!-- /.component --> 
          </div><!-- /.col-lg-6 -->  
            <div class="col-md-4">
              <div class="component">
              <%= image_tag "dashboard_leaf.png", class: "img-circle", alt: "leaves", width: 140, height: 140 %>
              <h3>Strategize</h3>
              <p>First look at the overall big picture and the break this down in to smaller details. Remember that you different experiences and knowledge, this experience and knowledge will open new possibilities and options.</p>
              <p><%= link_to 'Strategize', root_path, class: "btn btn-success" %></p>
            </div><!-- /.component -->              
          </div><!-- /.col-lg-6 -->   
        </div><!-- /.row  -->   
    </div><!-- col-sm-9 main -->

	</div><!-- row -->
</div><!-- container-fluid -->